spring:
  data:
    mongodb:
      uri: ${DB_URI}
      database: Cluster0
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

file:
  storage:
    type: 'local'
    local:
      directory: ${LOCAL_FILE_STORAGE_DIR}


server:
  port: 9093